name: KGTorrent
channels:
  - defaults
dependencies:
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=py37_0
  - openssl=1.1.1h=he774522_0
  - pip=20.2.4=py37_0
  - python=3.7.9=h60c2a47_0
  - setuptools=50.3.0=py37h9490d1a_1
  - sqlite=3.33.0=h2a8f88b_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wheel=0.35.1=py_0
  - wincertstore=0.2=py37_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.2.0
    - backcall==0.2.0
    - bleach==3.2.1
    - cffi==1.14.3
    - chardet==3.0.4
    - colorama==0.4.4
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - idna==2.10
    - importlib-metadata==2.0.0
    - ipykernel==5.3.4
    - ipython==7.18.1
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - jinja2==2.11.2
    - json5==0.9.5
    - jsonschema==3.2.0
    - jupyter-client==6.1.7
    - jupyter-core==4.6.3
    - jupyterlab==2.2.9
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==1.2.0
    - kaggle==1.5.10
    - markupsafe==1.1.1
    - mistune==0.8.4
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - nest-asyncio==1.4.1
    - notebook==6.1.4
    - numpy==1.19.2
    - packaging==20.4
    - pandas==1.1.3
    - pandocfilters==1.4.2
    - parso==0.7.1
    - pickleshare==0.7.5
    - prometheus-client==0.8.0
    - prompt-toolkit==3.0.8
    - pycparser==2.20
    - pygments==2.7.1
    - pymysql==0.10.1
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - python-slugify==4.0.1
    - pytz==2020.1
    - pywin32==228
    - pywinpty==0.5.7
    - pyzmq==19.0.2
    - requests==2.24.0
    - send2trash==1.5.0
    - six==1.15.0
    - sqlalchemy==1.3.20
    - sqlalchemy-utils==0.36.8
    - terminado==0.9.1
    - testpath==0.4.4
    - text-unidecode==1.3
    - tornado==6.0.4
    - tqdm==4.50.2
    - traitlets==5.0.5
    - urllib3==1.25.11
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - xlrd==1.2.0
    - zipp==3.3.1
prefix: /opt/anaconda3/envs/KGTorrent

